<a href="https://colab.research.google.com/github/FernandoCasco/etl-data-pipeline/blob/main/notebooks/Aseguradoras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/FernandoCasco/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv

In [1]:
import pandas as pd

In [17]:

url = "https://raw.githubusercontent.com/FernandoCasco/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"

aseguradoras = pd.read_csv(url)

aseguradoras.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [18]:
# Exploracion de datos

aseguradoras.info()
aseguradoras.columns
aseguradoras.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            13 non-null     object
 3   rating_riesgo   12 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

id_aseguradora    0
nombre            0
pais              2
rating_riesgo     3
dtype: int64

In [21]:

#Limpieza de datos

def limpiar_dataframe(df):

    df.columns = df.columns.str.strip().str.lower()

    for col in df.select_dtypes(include='object').columns:
        df[col] = df[col].astype(str).str.strip()

    df = df.replace(r'^\s*$', pd.NA, regex=True)

    df = df.drop_duplicates()

    return df

In [23]:
aseguradoras = limpiar_dataframe(aseguradoras)

In [24]:
aseguradoras.info()

aseguradoras.isnull().sum()

aseguradoras.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            15 non-null     object
 3   rating_riesgo   15 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           nan
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [26]:
aseguradoras['pais'] = aseguradoras['pais'].replace({
    "ElSalvador": "El Salvador"
})

In [34]:
#Transformaciones Normalizar nombres de países

aseguradoras['pais'] = aseguradoras['pais'].replace({
    "ElSalvador": "El Salvador"
})

In [33]:
#Normalizar texto (capitalización)
aseguradoras['pais'] = aseguradoras['pais'].str.title()
aseguradoras['nombre'] = aseguradoras['nombre'].str.title()

In [36]:
#Estandarizar valores de rating

aseguradoras['rating_riesgo'] = aseguradoras['rating_riesgo'].str.capitalize()

In [38]:
#Validar tipos de datos

aseguradoras['id_aseguradora'] = aseguradoras['id_aseguradora'].astype(int)

In [29]:
#Exportacion de de archivos curated

aseguradoras.to_csv("aseguradoras_curated.csv", index=False)